### ISSUE TITLE
Get stuck at preprocessing CC's JS data

### ISSUE THREAD

**Issue by gystar** [bayesgroup/code_transformers#8]
Hi, It's a very interesting and solid study. And I'm trying to reproduce it.
But when I run "bash src/scripts/preprocess_data.sh" in the "cc/main" folder, I get stuck.
The process hangs here for two days:
![image](https://user-images.githubusercontent.com/10754127/201806255-8e7d1a9f-843a-49f4-a491-f269998b831f.png)

**Comment by serjtroshin** [comment]
Hi! Thank you for your interest, could you try to run the script with `tree_rel="False"` option? Tree masks are most consuming… Let me know on your progress!

**Comment by gystar** [comment]
I can finish the preprocessing with the tree_rel="False" option.
Before this, I tried twice without that option but the preprocessing always hung.
I think there may be some bugs here, e.g., deadlock.
How can I conduct the experiment with the tree_rel="False" option?
![image](https://user-images.githubusercontent.com/10754127/202104332-9d561e35-065f-4d9f-bfa9-f70ccd204dbb.png)

**Comment by serjtroshin** [comment]
I wanted to clarify which model do you need? If you don't need Tree Relative Attention, then just try to run the script with `tree_rel="False"`. Otherwise, please try to monitor your resources, maybe you are out of RAM of disc space, tree attention masks are heavy, you may also try to monitor the progress in detail so that we can understand where it is stuck.

**Comment by gystar** [comment]
Thanks very much!
